title: Henrique Pettenuci
author:
  name: Henrique Pettenuci
  email: henrique@pettenuci.com
description: >-
  This is my personal website. A place that I use to share my daily experiences,
  projects and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pettenuci.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hmp_pc
github_username:  hpettenuci
linkedin_username: hpettenuci
google_analytics: G-8WS4RVS07C

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
